import state, { json, recordAudit } from "./_state.js";
function matches(device, rollout) { if (rollout.target_type === "device") return rollout.target_ids.includes(device.device_id); if (rollout.target_type === "establishment") return rollout.target_ids.includes(device.establishment_id); return rollout.target_ids.includes(device.batch_id); }
export default function handler(request, response) {
  if (request.method === "OPTIONS") return response.status(204).end();
  if (request.method === "GET") { const id = request.query.rollout_id; if (id) { const rollout = state.rollouts.find((r) => r.rollout_id === id) || null; return json(response, 200, { rollout, targets: rollout ? [...state.devices.values()].filter((d) => matches(d, rollout)) : [] }); } return json(response, 200, { rollouts: state.rollouts }); }
  if (request.method !== "POST") return json(response, 405, { error: "METHOD_NOT_ALLOWED" }); const body = typeof request.body === "string" ? JSON.parse(request.body || "{}") : request.body || {};
  if (!["device", "establishment", "batch"].includes(body.target_type) || !Array.isArray(body.target_ids) || !body.target_ids.length || !body.channel || !body.version) return json(response, 400, { error: "target_type, target_ids, channel y version son obligatorios" });
  const rollout = { rollout_id: `rollout-${Date.now()}`, target_type: body.target_type, target_ids: body.target_ids.map(String), channel: String(body.channel), version: String(body.version), requested_by: String(body.requested_by || "operator"), status: "PLANNED", created_at: new Date().toISOString() }; state.rollouts.unshift(rollout); const targets = [...state.devices.values()].filter((d) => matches(d, rollout)); recordAudit("OTA_ROLLOUT_CREATED", { actor: rollout.requested_by, rollout_id: rollout.rollout_id, target_type: rollout.target_type, target_ids: rollout.target_ids, target_count: targets.length, version: rollout.version, channel: rollout.channel }); return json(response, 201, { rollout, target_count: targets.length, targets });
}
